name: ðŸ“Š Profile Metrics
on:
  schedule: [{ cron: "0 */6 * * *" }]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # allow commit
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: aryansharma2709
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # ðŸ‘‡ IMPORTANT: commit to main (default 'master' hota hai)
          committer_branch: main
          committer_message: "chore: update metrics [skip ci]"
          filename: metrics/metrics.svg

          plugins: |
            isocalendar, languages, habits, followup, wakatime
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, languages, editors
          plugin_wakatime_limit: 5
