name: ğŸ Generate Snake
on:
  workflow_dispatch:
  schedule: [{ cron: "0 */12 * * *" }]
  push: { branches: ["main"] }

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # allow pushing to output branch
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: aryansharma2709
          outputs: |
            dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
